# Generated by Django 4.0.3 on 2022-03-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('recommend', 'recommend'), ('inquiry', 'Sophomore'), ('report', 'report'), ('complaint', 'complaint'), ('other', 'other')], max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
