# Generated by Django 4.0.3 on 2022-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0002_comment_created_comment_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('feedback', models.JSONField(default=dict)),
                ('other_feedback', models.TextField(blank=True)),
            ],
        ),
    ]
