# Generated by Django 4.0.3 on 2022-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('interested', 'interested'), ('recommend', 'recommend'), ('inquiry', 'Sophomore'), ('report', 'report'), ('complaint', 'complaint'), ('other', 'other')], max_length=255),
        ),
    ]
